[package]
name = "repaint-server-fcm"
version = "1.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1.73"
repaint-server-usecase = { path = "../usecase" }
reqwest = { version = "0.11.20", default-features = false, features = [
  "rustls-tls",
] }
serde_json = "1.0.107"
teloc = "0.2.0"
