services:
  db:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: local-db
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"
      interval: "5s"
      timeout: "5s"
      retries: 3
      start_period: "5s"
  wait_for_db:
    image: alpine:3.18.2
    entrypoint: /bin/sh
    command: -c "echo -n 'db started';echo"
    depends_on:
      db:
        condition: service_healthy
