{
 "title": "PostgreSQL Query",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Max exec time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT max_exec_time, mean_exec_time, calls, query FROM pg_stat_statements order by max_exec_time desc limit 50;"
    }
   ]
  },
  {
   "title": "Calls",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT max_exec_time, mean_exec_time, calls, query FROM pg_stat_statements order by calls desc limit 50;"
    }
   ]
  },
  {
   "title": "Mean exec time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT max_exec_time, mean_exec_time, calls, query FROM pg_stat_statements order by mean_exec_time desc limit 50;"
    }
   ]
  }
 ]
}