[package]
name = "repaint-server-core"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
email_address = "0.2.4"
repaint-server-model = { path = "../model" }
serde = "1.0.178"
serde_json = "1.0.104"
tracing = "0.1.37"

[dependencies.sea-orm]
version = "0.12.1"
features = ["runtime-tokio-rustls", "sqlx-postgres", "postgres-array"]
