[package]
name = "repaint-server-core"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1.37"

[dependencies.sea-orm]
version = "0.11.3"
features = ["runtime-tokio-rustls", "sqlx-postgres"]
