[package]
name = "repaint-server-usecase"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.73"
email_address = "0.2.4"
futures = "0.3.28"
rand = "0.8.5"
repaint-server-model = { path = "../model" }
serde = { version = "1.0.183", features = ["derive"] }
teloc = "0.2.0"
thiserror = "1.0.44"
