[package]
name = "repaint-server-auth0"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
jsonwebtoken = "8.3.0"
reqwest = { version = "0.11.20", default-features = false, features = [
  "rustls-tls",
] }
serde = "1.0.188"
