//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "admins")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub admin_id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        super::events_admins::Relation::Events.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::events_admins::Relation::Admins.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
