apiVersion: 1

datasources:
  - name: postgres
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    jsonData:
      sslmode: disable
    database: local-db
    user: user
    secureJsonData:
      password: pass
