apiVersion: 1

datasources:
  - name: postgres
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    jsonData:
      sslmode: disable
    database: {{POSTGRES_DB}}
    user: {{POSTGRES_USER}} 
    editable: true 
    secureJsonData:
      password: {{POSTGRES_PASSWORD}}
