name: Security audit

on:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
jobs:
  security_audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans sources
        #  - bans licenses sources
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4.1.0
      - name: Test | Security Audit
        uses: EmbarkStudios/cargo-deny-action@v1.5.5
        with:
          command: check ${{ matrix.checks }}
