name: Main workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10
  MACOSX_DEPLOYMENT_TARGET: 10.7

jobs:
  rustfmt:
    name: Rustfmt [Formatter]
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: "nightly-2023-07-15"
          components: rustfmt
      - name: Build | Format
        run: cargo fmt --all -- --check
  clippy:
    name: Clippy [Linter]
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: "nightly-2023-07-15"
          components: clippy
      - name: Setup | Cache
        uses: Swatinem/rust-cache@v2.7.1
      - name: Build | Lint
        uses: giraffate/clippy-action@871cc4173f2594435c7ea6b0bce499cf6c2164a1
  cargo_check:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: "nightly-2023-07-15"
      - name: Setup | Cache
        uses: Swatinem/rust-cache@v2.7.1
      - name: Build | Check
        run: cargo check --workspace --locked
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: "nightly-2023-07-15"
      - name: Setup | Just
        uses: taiki-e/install-action@v2.20.17
        with:
          tool: just@1.14.0
      - name: Setup | Cache
        uses: Swatinem/rust-cache@v2.7.1
      - name: Build | Test
        run: just test
