name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - name: Setup OS
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
      - name: Setup Git
        run: |
          sudo apt-get install -y git
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - name: Setup GitHub App
        id: bot
        uses: re-taro/actions/gen-installation-token@v3.3.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: google-github-actions/release-please-action@v3.7.11
        id: release
        with:
          release-type: rust
          package-name: repaint-server
          token: ${{ steps.bot.outputs.token }}
      - name: Publish the Docker package
        if: steps.release.outputs.releases_created
        uses: re-taro/actions/docker-publish@v3.3.0
        with:
          images: ghcr.io/after-school-garbage-squad/repaint-server
          major: ${{ steps.release.outputs.major }}
          minor: ${{ steps.release.outputs.minor }}
          patch: ${{ steps.release.outputs.patch }}
          sha: ${{ steps.release.outputs.sha }}
      - name: Revoke GitHub Apps token
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
        run: |
          curl --location --silent --request DELETE \
            --url "${GITHUB_API_URL}/installation/token" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${GITHUB_TOKEN}"
